/**
 * How artifacts are described and arranged on screen — the pure half of the
 * Artifacts screens, so it can be tested without a renderer.
 */

import type { Artifact, ArtifactKind, ArtifactShare } from '@/domain'

const DAY = 24 * 60 * 60 * 1000

/** One glyph per kind. `Record` so a new kind does not compile without one. */
export const ARTIFACT_GLYPH: Record<ArtifactKind, string> = {
  image: 'image',
  video: 'film',
  audio: 'music',
  document: 'file-lines',
  code: 'code',
  data: 'table',
  other: 'file'
}

const KIND_LABEL: Record<ArtifactKind, string> = {
  image: 'Image',
  video: 'Video',
  audio: 'Audio',
  document: 'Document',
  code: 'Code',
  data: 'Data',
  other: 'File'
}

export function kindLabel(kind: ArtifactKind): string {
  return KIND_LABEL[kind]
}

/** `812 B`, `4.3 KB`, `1.2 MB`. One decimal, dropped when it would be `.0`. */
export function formatBytes(size: number): string {
  if (!Number.isFinite(size) || size < 0) return '—'
  if (size < 1024) return `${Math.round(size)} B`

  const units = ['KB', 'MB', 'GB']
  let value = size / 1024
  let unit = 0

  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024
    unit += 1
  }

  const rounded = value >= 100 ? Math.round(value).toString() : value.toFixed(1).replace(/\.0$/, '')

  return `${rounded} ${units[unit]}`
}

export type ArtifactFilter = 'all' | 'images' | 'documents' | 'code' | 'sent'

export const ARTIFACT_FILTERS: { key: ArtifactFilter; label: string }[] = [
  { key: 'all', label: 'All' },
  { key: 'images', label: 'Images' },
  { key: 'documents', label: 'Documents' },
  { key: 'code', label: 'Code' },
  { key: 'sent', label: 'Sent' }
]

/**
 * Filters are about what a person is looking for, not the host's taxonomy:
 * "documents" takes data files along with prose, since a CSV the agent wrote
 * is looked for in the same mood as the report beside it. "Sent" cuts across
 * kinds — it is every picture that came *from* this app.
 */
export function matchesArtifactFilter(artifact: Artifact, filter: ArtifactFilter): boolean {
  switch (filter) {
    case 'all':
      return true
    case 'images':
      return artifact.kind === 'image' || artifact.kind === 'video'
    case 'documents':
      return artifact.kind === 'document' || artifact.kind === 'data' || artifact.kind === 'other'
    case 'code':
      return artifact.kind === 'code'
    case 'sent':
      return artifact.origin === 'upload'
  }
}

export interface ArtifactGroup {
  label: string
  artifacts: Artifact[]
}

/**
 * Group by the day something last changed: Today, Yesterday, then dates.
 *
 * Keeps the input's order inside each group, so a list the host sorted newest
 * first stays that way. A different year gets the year on the label, since
 * "Mar 3" a year on is not the same day.
 */
export function groupArtifactsByDay(artifacts: Artifact[], now = Date.now()): ArtifactGroup[] {
  const startOfToday = new Date(now)
  startOfToday.setHours(0, 0, 0, 0)

  const today = startOfToday.getTime()
  const yesterday = today - DAY
  const thisYear = startOfToday.getFullYear()

  const groups: ArtifactGroup[] = []
  const byLabel = new Map<string, ArtifactGroup>()

  for (const artifact of artifacts) {
    const at = artifact.updatedAt || artifact.createdAt
    let label: string

    if (at >= today) label = 'Today'
    else if (at >= yesterday) label = 'Yesterday'
    else {
      const date = new Date(at)

      label = date.toLocaleDateString(undefined, {
        month: 'short',
        day: 'numeric',
        ...(date.getFullYear() === thisYear ? {} : { year: 'numeric' })
      })
    }

    let group = byLabel.get(label)

    if (!group) {
      group = { label, artifacts: [] }
      byLabel.set(label, group)
      groups.push(group)
    }

    group.artifacts.push(artifact)
  }

  return groups
}

/** Tools whose output is generated rather than written, for the provenance line. */
const GENERATORS = new Set(['image_gen', 'image_generate', 'generate_image', 'video_gen', 'generate_video'])

/**
 * The tools whose finishing means an artifact may exist.
 *
 * Mirrors `ARTIFACT_TOOLS` in the host plugin's `adapter.py` — the app cannot
 * ask the host which tools it captures, so this is what tells the chat when a
 * settled tool call is worth re-reading the session's artifacts for.
 */
export const ARTIFACT_TOOLS: ReadonlySet<string> = new Set(['write_file', ...GENERATORS])

/** Where it came from, in one line: `Sent from this app`, `Written by write_file`. */
export function describeOrigin(artifact: Pick<Artifact, 'origin' | 'tool'>): string {
  if (artifact.origin === 'upload') return 'Sent from this app'
  if (!artifact.tool) return 'Produced by the agent'
  if (GENERATORS.has(artifact.tool)) return `Generated by ${artifact.tool}`

  return `Written by ${artifact.tool}`
}

/** Largest text artifact the detail screen renders inline. */
export const TEXT_PREVIEW_LIMIT = 200 * 1024

const TEXT_MIMES = new Set(['application/json', 'application/jsonl', 'application/yaml', 'application/toml', 'application/xml', 'application/x-sh', 'application/javascript'])

/** Whether the bytes are worth showing as text on the detail screen. */
export function isTextLike(artifact: Pick<Artifact, 'kind' | 'mimeType' | 'size'>): boolean {
  if (artifact.size > TEXT_PREVIEW_LIMIT) return false
  if (artifact.kind === 'image' || artifact.kind === 'video' || artifact.kind === 'audio') return false

  return artifact.mimeType.startsWith('text/') || TEXT_MIMES.has(artifact.mimeType)
}

/**
 * What a share link is good for, said under the button.
 *
 * The plain truth from `docs/artifacts.md` §5: the link opens for anyone who
 * can already reach the host, and the host's own sign-in is what stands
 * between it and the open internet. The file itself goes to outsiders through
 * the share sheet, which is the other button.
 */
export function shareCaption(share: ArtifactShare | null, hostName: string): string {
  if (!share) return `Anyone signed in to ${hostName} can open a link. To send the file itself, use Share file.`

  if (share.expiresAt !== null) {
    const remaining = share.expiresAt - Date.now()

    if (remaining <= 0) return 'This link has expired. Sharing again mints a new one.'

    const hours = Math.max(1, Math.round(remaining / (60 * 60 * 1000)))

    return `Link is live for ${hours}h more, for anyone signed in to ${hostName}.`
  }

  return `Link is live until you stop sharing, for anyone signed in to ${hostName}.`
}
