/**
 * How artifacts are described and arranged on screen — the pure half of the
 * Artifacts screens, so it can be tested without a renderer.
 */

import type { Artifact, ArtifactKind, ArtifactShare } from '@/domain'

const DAY = 24 * 60 * 60 * 1000

/** One glyph per kind. `Record` so a new kind does not compile without one. */
export const ARTIFACT_GLYPH: Record<ArtifactKind, string> = {
  image: 'image',
  video: 'film',
  audio: 'music',
  document: 'file-lines',
  code: 'code',
  data: 'table',
  other: 'file'
}

const KIND_LABEL: Record<ArtifactKind, string> = {
  image: 'Image',
  video: 'Video',
  audio: 'Audio',
  document: 'Document',
  code: 'Code',
  data: 'Data',
  other: 'File'
}

export function kindLabel(kind: ArtifactKind): string {
  return KIND_LABEL[kind]
}

/** `812 B`, `4.3 KB`, `1.2 MB`. One decimal, dropped when it would be `.0`. */
export function formatBytes(size: number): string {
  if (!Number.isFinite(size) || size < 0) return '—'
  if (size < 1024) return `${Math.round(size)} B`

  const units = ['KB', 'MB', 'GB']
  let value = size / 1024
  let unit = 0

  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024
    unit += 1
  }

  const rounded = value >= 100 ? Math.round(value).toString() : value.toFixed(1).replace(/\.0$/, '')

  return `${rounded} ${units[unit]}`
}

export type ArtifactFilter = 'all' | 'images' | 'documents' | 'sent'

export const ARTIFACT_FILTERS: { key: ArtifactFilter; label: string }[] = [
  { key: 'all', label: 'All' },
  { key: 'images', label: 'Images' },
  { key: 'documents', label: 'Documents' },
  { key: 'sent', label: 'Sent' }
]

/**
 * Filters are about what a person is looking for, not the host's taxonomy:
 * "documents" takes data files along with prose, since a CSV the agent wrote
 * is looked for in the same mood as the report beside it. "Sent" cuts across
 * kinds — it is every picture that came *from* this app.
 *
 * No "Code" filter: the host no longer files source the agent writes (it is
 * for the toolchain, not for a person), so the chip would be empty. The kind
 * itself stays in the taxonomy for rows stored before that rule, which show
 * under "All" with their own glyph.
 */
export function matchesArtifactFilter(artifact: Artifact, filter: ArtifactFilter): boolean {
  switch (filter) {
    case 'all':
      return true
    case 'images':
      return artifact.kind === 'image' || artifact.kind === 'video'
    case 'documents':
      return artifact.kind === 'document' || artifact.kind === 'data' || artifact.kind === 'other'
    case 'sent':
      return artifact.origin === 'upload'
  }
}

export interface ArtifactGroup {
  label: string
  artifacts: Artifact[]
}

/**
 * Group by the day something last changed: Today, Yesterday, then dates.
 *
 * Keeps the input's order inside each group, so a list the host sorted newest
 * first stays that way. A different year gets the year on the label, since
 * "Mar 3" a year on is not the same day.
 */
export function groupArtifactsByDay(artifacts: Artifact[], now = Date.now()): ArtifactGroup[] {
  const startOfToday = new Date(now)
  startOfToday.setHours(0, 0, 0, 0)

  const today = startOfToday.getTime()
  const yesterday = today - DAY
  const thisYear = startOfToday.getFullYear()

  const groups: ArtifactGroup[] = []
  const byLabel = new Map<string, ArtifactGroup>()

  for (const artifact of artifacts) {
    const at = artifact.updatedAt || artifact.createdAt
    let label: string

    if (at >= today) label = 'Today'
    else if (at >= yesterday) label = 'Yesterday'
    else {
      const date = new Date(at)

      label = date.toLocaleDateString(undefined, {
        month: 'short',
        day: 'numeric',
        ...(date.getFullYear() === thisYear ? {} : { year: 'numeric' })
      })
    }

    let group = byLabel.get(label)

    if (!group) {
      group = { label, artifacts: [] }
      byLabel.set(label, group)
      groups.push(group)
    }

    group.artifacts.push(artifact)
  }

  return groups
}

/** Tools whose output is generated rather than written, for the provenance line. */
const GENERATORS = new Set(['image_gen', 'image_generate', 'generate_image', 'video_gen', 'generate_video'])

/**
 * The tools whose finishing means an artifact may exist.
 *
 * Mirrors `ARTIFACT_TOOLS` in the host plugin's `adapter.py` — the app cannot
 * ask the host which tools it captures, so this is what tells the chat when a
 * settled tool call is worth re-reading the session's artifacts for.
 */
export const ARTIFACT_TOOLS: ReadonlySet<string> = new Set(['write_file', ...GENERATORS])

/** Where it came from, in one line: `Sent from this app`, `Written by write_file`. */
export function describeOrigin(artifact: Pick<Artifact, 'origin' | 'tool'>): string {
  if (artifact.origin === 'upload') return 'Sent from this app'
  if (!artifact.tool) return 'Produced by the agent'
  if (GENERATORS.has(artifact.tool)) return `Generated by ${artifact.tool}`

  return `Written by ${artifact.tool}`
}

/** Largest text artifact the detail screen renders inline. */
export const TEXT_PREVIEW_LIMIT = 200 * 1024

const TEXT_MIMES = new Set(['application/json', 'application/jsonl', 'application/yaml', 'application/toml', 'application/xml', 'application/x-sh', 'application/javascript'])

/** Whether the bytes are worth showing as text on the detail screen. */
export function isTextLike(artifact: Pick<Artifact, 'kind' | 'mimeType' | 'size'>): boolean {
  if (artifact.size > TEXT_PREVIEW_LIMIT) return false
  if (artifact.kind === 'image' || artifact.kind === 'video' || artifact.kind === 'audio') return false

  return artifact.mimeType.startsWith('text/') || TEXT_MIMES.has(artifact.mimeType)
}

/**
 * Whether the artifact opens as a rendered page: a sheet with the page in a
 * WebView, instead of the detail screen.
 *
 * MIME first, then the name — a host that hands over a bare `application/
 * octet-stream` for a file called `report.html` still has a page worth
 * rendering, and a `text/plain` that is really HTML is a rarer mistake than
 * the reverse, so the name only widens the set.
 */
export function isHtmlArtifact(artifact: Pick<Artifact, 'name' | 'mimeType'>): boolean {
  if (artifact.mimeType === 'text/html') return true

  return /\.(html?|xhtml)$/i.test(artifact.name)
}

/**
 * How the preview sheet draws an artifact: as a web page, a PDF, rendered
 * markdown, or a table read from delimited text.
 */
export type PreviewMode = 'page' | 'pdf' | 'markdown' | 'csv' | 'tsv'

/**
 * Whether — and as what — an artifact opens in the preview sheet rather than
 * on the detail screen. `null` is the detail screen.
 *
 * The same judgement as {@link isHtmlArtifact} for every type: MIME first,
 * name second, since a host that says `application/octet-stream` for
 * `notes.md` still owes rendered prose. Text that is read and laid out here
 * (markdown, tables) stops at `TEXT_PREVIEW_LIMIT`, like the detail screen's
 * inline text does; a page or a PDF has no such cap, since a WebView streams
 * those itself. PDFs only where the caller says the platform's WebView can
 * draw one — iOS can, Android's cannot — so `pdfInSheet` is the caller's
 * platform, not a preference.
 */
export function previewMode(artifact: Pick<Artifact, 'name' | 'mimeType' | 'size'>, pdfInSheet: boolean): PreviewMode | null {
  if (isHtmlArtifact(artifact)) return 'page'

  const name = artifact.name.toLowerCase()

  if (artifact.mimeType === 'application/pdf' || name.endsWith('.pdf')) return pdfInSheet ? 'pdf' : null
  if (artifact.size > TEXT_PREVIEW_LIMIT) return null
  if (artifact.mimeType === 'text/markdown' || /\.(md|markdown)$/.test(name)) return 'markdown'
  if (artifact.mimeType === 'text/csv' || name.endsWith('.csv')) return 'csv'
  if (artifact.mimeType === 'text/tab-separated-values' || name.endsWith('.tsv')) return 'tsv'

  return null
}

/**
 * Delimited text as rows of cells, the way a spreadsheet would read it.
 *
 * RFC 4180 without ceremony: a cell in double quotes may hold the delimiter,
 * line breaks and doubled quotes; a bare cell ends at the delimiter or the
 * line. Both line endings are taken. A trailing newline does not make an
 * empty last row, but an empty line in the middle does keep its place, since
 * a spreadsheet would show it too.
 */
export function parseDelimited(text: string, delimiter: string): string[][] {
  const rows: string[][] = []
  let row: string[] = []
  let cell = ''
  let quoted = false
  let i = 0

  while (i < text.length) {
    const char = text[i]

    if (quoted) {
      if (char === '"') {
        if (text[i + 1] === '"') {
          cell += '"'
          i += 2

          continue
        }

        quoted = false
        i += 1

        continue
      }

      cell += char
      i += 1

      continue
    }

    if (char === '"' && cell === '') {
      quoted = true
      i += 1

      continue
    }

    if (char === delimiter) {
      row.push(cell)
      cell = ''
      i += 1

      continue
    }

    if (char === '\r' || char === '\n') {
      row.push(cell)
      rows.push(row)
      row = []
      cell = ''
      i += char === '\r' && text[i + 1] === '\n' ? 2 : 1

      continue
    }

    cell += char
    i += 1
  }

  if (cell !== '' || row.length > 0) {
    row.push(cell)
    rows.push(row)
  }

  return rows
}

/**
 * What a share link is good for, said under the button.
 *
 * The plain truth from `docs/artifacts.md` §5: the link opens for anyone who
 * can already reach the host, and the host's own sign-in is what stands
 * between it and the open internet. The file itself goes to outsiders through
 * the share sheet, which is the other button.
 */
export function shareCaption(share: ArtifactShare | null, hostName: string): string {
  if (!share) return `Anyone signed in to ${hostName} can open a link. To send the file itself, use Share file.`

  if (share.expiresAt !== null) {
    const remaining = share.expiresAt - Date.now()

    if (remaining <= 0) return 'This link has expired. Sharing again mints a new one.'

    const hours = Math.max(1, Math.round(remaining / (60 * 60 * 1000)))

    return `Link is live for ${hours}h more, for anyone signed in to ${hostName}.`
  }

  return `Link is live until you stop sharing, for anyone signed in to ${hostName}.`
}
