/**
 * The pure half of the Artifacts screens: how files are labelled, filtered
 * and grouped. The rendering is not under test; the decisions it draws are.
 */

import { describe, expect, it } from '@jest/globals'

import type { Artifact, ArtifactKind } from '@/domain'
import {
  ARTIFACT_FILTERS,
  ARTIFACT_GLYPH,
  describeOrigin,
  formatBytes,
  groupArtifactsByDay,
  isHtmlArtifact,
  isTextLike,
  matchesArtifactFilter,
  shareCaption
} from '@/ui/artifacts'

const HOUR = 60 * 60 * 1000
const DAY = 24 * HOUR

function artifact(overrides: Partial<Artifact> = {}): Artifact {
  return {
    id: 'a1',
    name: 'report.md',
    kind: 'document',
    mimeType: 'text/markdown',
    size: 4312,
    sessionId: 'ses-1',
    origin: 'agent',
    tool: 'write_file',
    sourcePath: '/home/agent/report.md',
    createdAt: 1_000,
    updatedAt: 1_000,
    version: 1,
    share: null,
    ...overrides
  }
}

describe('formatBytes', () => {
  it('picks the unit that reads naturally and drops a trailing .0', () => {
    expect(formatBytes(812)).toBe('812 B')
    expect(formatBytes(4312)).toBe('4.2 KB')
    expect(formatBytes(1024)).toBe('1 KB')
    expect(formatBytes(1.2 * 1024 * 1024)).toBe('1.2 MB')
    expect(formatBytes(250 * 1024 * 1024)).toBe('250 MB')
  })

  it('does not invent a size it was not given', () => {
    expect(formatBytes(-1)).toBe('—')
    expect(formatBytes(Number.NaN)).toBe('—')
  })
})

describe('ARTIFACT_GLYPH', () => {
  it('has a glyph for every kind the host can answer with', () => {
    const kinds: ArtifactKind[] = ['image', 'video', 'audio', 'document', 'code', 'data', 'other']

    for (const kind of kinds) expect(ARTIFACT_GLYPH[kind]).toBeTruthy()
  })
})

describe('matchesArtifactFilter', () => {
  it('sorts by what a person is looking for rather than by the host taxonomy', () => {
    const image = artifact({ kind: 'image' })
    const video = artifact({ kind: 'video' })
    const csv = artifact({ kind: 'data' })
    const script = artifact({ kind: 'code' })
    const sent = artifact({ kind: 'image', origin: 'upload', tool: null })

    expect(matchesArtifactFilter(image, 'images')).toBe(true)
    expect(matchesArtifactFilter(video, 'images')).toBe(true)
    expect(matchesArtifactFilter(csv, 'documents')).toBe(true)
    expect(matchesArtifactFilter(script, 'code')).toBe(true)
    expect(matchesArtifactFilter(script, 'documents')).toBe(false)
    expect(matchesArtifactFilter(sent, 'sent')).toBe(true)
    expect(matchesArtifactFilter(image, 'sent')).toBe(false)
  })

  it('offers every filter it can answer', () => {
    for (const { key } of ARTIFACT_FILTERS) {
      expect(matchesArtifactFilter(artifact(), key)).toBe(key === 'all' || key === 'documents')
    }
  })
})

describe('groupArtifactsByDay', () => {
  const now = new Date(2026, 8, 7, 15, 30).getTime()

  it('labels today and yesterday by name and older days by date, keeping order', () => {
    const rows = [
      artifact({ id: 'now', updatedAt: now - HOUR }),
      artifact({ id: 'earlier-today', updatedAt: now - 5 * HOUR }),
      artifact({ id: 'yesterday', updatedAt: now - DAY }),
      artifact({ id: 'last-week', updatedAt: now - 6 * DAY }),
      artifact({ id: 'last-year', updatedAt: now - 400 * DAY })
    ]

    const groups = groupArtifactsByDay(rows, now)

    expect(groups.map(group => group.label)).toEqual(['Today', 'Yesterday', 'Sep 1', 'Aug 3, 2025'])
    expect(groups[0].artifacts.map(row => row.id)).toEqual(['now', 'earlier-today'])
  })

  it('groups by the last change, not the first', () => {
    const rewritten = artifact({ createdAt: now - 10 * DAY, updatedAt: now - HOUR, version: 3 })

    expect(groupArtifactsByDay([rewritten], now)[0].label).toBe('Today')
  })

  it('has nothing to say about nothing', () => {
    expect(groupArtifactsByDay([], now)).toEqual([])
  })
})

describe('describeOrigin', () => {
  it('names the tool, and says generated for the generators', () => {
    expect(describeOrigin({ origin: 'agent', tool: 'write_file' })).toBe('Written by write_file')
    expect(describeOrigin({ origin: 'agent', tool: 'image_generate' })).toBe('Generated by image_generate')
    expect(describeOrigin({ origin: 'agent', tool: null })).toBe('Produced by the agent')
    expect(describeOrigin({ origin: 'upload', tool: null })).toBe('Sent from this app')
  })
})

describe('isTextLike', () => {
  it('previews prose, code and data inline, but never pictures or anything large', () => {
    expect(isTextLike({ kind: 'document', mimeType: 'text/markdown', size: 100 })).toBe(true)
    expect(isTextLike({ kind: 'code', mimeType: 'text/typescript', size: 100 })).toBe(true)
    expect(isTextLike({ kind: 'data', mimeType: 'application/json', size: 100 })).toBe(true)
    expect(isTextLike({ kind: 'image', mimeType: 'image/svg+xml', size: 100 })).toBe(false)
    expect(isTextLike({ kind: 'document', mimeType: 'application/pdf', size: 100 })).toBe(false)
    expect(isTextLike({ kind: 'document', mimeType: 'text/plain', size: 5 * 1024 * 1024 })).toBe(false)
  })
})

describe('isHtmlArtifact', () => {
  it('opens pages as pages', () => {
    expect(isHtmlArtifact({ name: 'report.html', mimeType: 'text/html' })).toBe(true)
    expect(isHtmlArtifact({ name: 'report.htm', mimeType: 'text/html' })).toBe(true)
    // A host that hands the file over as bare octet-stream still owes a page.
    expect(isHtmlArtifact({ name: 'report.html', mimeType: 'application/octet-stream' })).toBe(true)
    expect(isHtmlArtifact({ name: 'Report.HTML', mimeType: 'application/octet-stream' })).toBe(true)
    expect(isHtmlArtifact({ name: 'index.xhtml', mimeType: 'application/octet-stream' })).toBe(true)
    // The name only widens the set: an html that is not a page does not get
    // the sheet, and neither does a page that is not html.
    expect(isHtmlArtifact({ name: 'html-cheatsheet.md', mimeType: 'text/markdown' })).toBe(false)
    expect(isHtmlArtifact({ name: 'notes.txt', mimeType: 'text/plain' })).toBe(false)
    expect(isHtmlArtifact({ name: 'notes.txt', mimeType: 'text/html' })).toBe(true)
  })
})

describe('shareCaption', () => {
  it('tells the truth about who a link reaches', () => {
    expect(shareCaption(null, 'hermes')).toContain('signed in to hermes')
    expect(shareCaption({ url: 'x', expiresAt: null, createdAt: 1 }, 'hermes')).toContain('until you stop sharing')
    expect(shareCaption({ url: 'x', expiresAt: Date.now() + 5 * HOUR, createdAt: 1 }, 'hermes')).toMatch(/live for \dh more/)
    expect(shareCaption({ url: 'x', expiresAt: Date.now() - 1, createdAt: 1 }, 'hermes')).toContain('expired')
  })
})
